name: Request
description: Request a service to be added/updated
labels: ["request"]
body:
  - type: dropdown
    attributes:
      description: "Select type of request against the service"
      label: "Request"
      options:
        - "Addition"
        - "Update"
        - "Deletion"
    validations:
      required: true