name: Request
description: Request a service to be added/updated
labels: ["request"]
body:
  - type: dropdown
    attributes:
      label: "Selection request type"
      options:
        - "Addition"
        - "Update"
        - "Deletion"